### ISSUE TITLE
Error when run the exe

### ISSUE THREAD

**Issue by bembee** [KovacsGG/pyI2L#1]
Hello
I got this error, when I run the pyI2L.exe (with the prebuilt or if I build it):
```shell
Traceback (most recent call last):
  File "pyI2L\__main__.py", line 30, in <module>
  File "argparse.py", line 1891, in parse_args
  File "argparse.py", line 1924, in parse_known_args
  File "argparse.py", line 2164, in _parse_known_args
  File "argparse.py", line 2653, in error
  File "argparse.py", line 2621, in print_usage
  File "argparse.py", line 2587, in format_usage
  File "argparse.py", line 286, in format_help
  File "argparse.py", line 217, in format_help
  File "argparse.py", line 303, in _format_usage
KeyError: 'PROG'
[5488] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by KovacsGG** [comment]
Thanks! I opened up the project and the fix for this was already there but not committed. I have no memory of doing it. It's strange that I didn't find the issue before release to begin with. I might have to invest in a CO detector...

2.1.1 actually works.
